# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

stage0 = Stage.create(board: "So..x\r\noo...\r\n....G\r\n.....\r\n.....\r\n")
stage1 = Stage.create(board: "S....x\r\nxx...x\r\n..xx..\r\n.x.G..\r\n.x....\r\n...xx.\r\n")
stage2 = Stage.create(board: "S...xo\r\n.....o\r\n..x..o\r\nx.G..o\r\n.....x\r\n......\r\n")
stage3 = Stage.create(board: "S.x.x.\r\n.....x\r\n......\r\nx.....\r\n...xGx\r\n......\r\n")
stage4 = Stage.create(board: "S.x...x\r\n.......\r\n...x...\r\n......x\r\n.x.G...\r\n......x\r\n..x..x.\r\n")
stage5 = Stage.create(board: "S...x..\r\n..x....\r\n......x\r\n.......\r\nx......\r\n.....x.\r\nGx.....\r\n")
stage6 = Stage.create(board: "S.....x.\r\n....x...\r\nx....x..\r\nx......x\r\n......x.\r\n......Gx\r\n........\r\n..x..x..\r\n")
stage7 = Stage.create(board: "S.......\r\n....xx..\r\n...x...x\r\n........\r\nx.......\r\n..x.....\r\n.G..x..o\r\n....x.x.\r\n")
stage8 = Stage.create(board: "S.x.....\r\n........\r\n.x.....x\r\n...xx...\r\n........\r\n.......x\r\nx..G..x.\r\n.....x..\r\n")
stage9 = Stage.create(board: "S......x.\r\n...x.x...\r\nx........\r\n........x\r\n...x..o..\r\n.........\r\n....xx.x.\r\n.G.x.....\r\n.x......x\r\n")
stage10 = Stage.create(board: "S........\r\n......x..\r\n...x.xx..\r\n..G...x..\r\n..x.....x\r\nx........\r\n...x.....\r\n........x\r\n.xx....x.\r\n")
stage11 = Stage.create(board: "S.x..x....\r\n....x.....\r\n..x....G.x\r\n..........\r\n.x........\r\n...x.x....\r\n..........\r\n..........\r\n..........\r\nx....x....\r\n")
stage12 = Stage.create(board: "S.......x.\r\n..x.......\r\n.x...x...x\r\n...x.....x\r\n..........\r\n.......xx.\r\n..x.......\r\n......G...\r\n..x.......\r\n....x.....\r\n")
stage13 = Stage.create(board: "S.........\r\n.x........\r\n.xx..x....\r\n....x.....\r\n..x.....x.\r\n.x....x...\r\n.......xGx\r\n.........x\r\n..........\r\n...x..x...\r\n")
stage14 = Stage.create(board: "Sx...x....\r\n...x.....x\r\n..x.......\r\n.xG.....x.\r\n......x.x.\r\n....x.....\r\nx.xx......\r\n.........x\r\n.x........\r\n..........\r\n")
stage15 = Stage.create(board: "S....x...\r\n....x....\r\n.....G...\r\n..x......\r\n......x.x\r\n.........\r\n.........\r\nx........\r\n...x..x..\r\n")
stage16 = Stage.create(board: "S.........\r\n.....x....\r\n........x.\r\n...x.Gx...\r\nx.........\r\n.........x\r\n...x....xx\r\n.x..x.....\r\nx.........\r\n.......x..\r\n")
stage17 = Stage.create(board: "S........x\r\nx........x\r\n........xx\r\n..x.......\r\nxx....xxx.\r\n....xG....\r\nx..x......\r\n...x......\r\n.x.x.....x\r\n..........\r\n")
stage18 = Stage.create(board: "S...x.....\r\n........x.\r\n.....x....\r\n.....G...x\r\n..........\r\nx.........\r\n......x...\r\n..........\r\n..x.......\r\n...x......\r\n")
stage19 = Stage.create(board: "S.x.....x.\r\n..........\r\n.......x..\r\n....x....x\r\n....x.x...\r\n.....x....\r\n...xG....x\r\nx.xx.x....\r\n......x...\r\n.......x..\r\n")
stage20 = Stage.create(board: "S.....x...\r\n.....x....\r\nx..x......\r\n..x..x....\r\n.Gx.xx...x\r\n.x..x.....\r\n..........\r\nx.........\r\n......x...\r\n.......x..\r\n")
stage21 = Stage.create(board: "Sx..x....x\r\n......x...\r\n..........\r\nx........x\r\nx.........\r\n..........\r\n......G..x\r\n.x........\r\n..........\r\n.x.x......\r\n")
stage22 = Stage.create(board: "S..x..x...\r\n..xx......\r\nx.....G...\r\n......x...\r\n..........\r\n...x......\r\nx......x..\r\n..........\r\n..x.....x.\r\n..x.....x.\r\n")
stage23 = Stage.create(board: "S..........\r\n.......x...\r\n..........x\r\n....x......\r\nx..........\r\n...........\r\n........x..\r\n...x.......\r\nx......x...\r\nG..........\r\nx........x.\r\n")
stage24 = Stage.create(board: "S.........x\r\n..x........\r\n...........\r\n.x....x.x.x\r\n...x....x..\r\n...G.......\r\n.....x.....\r\nx..xx..xx..\r\n....x......\r\n.x........x\r\n......x....\r\n")
stage25 = Stage.create(board: "S.....x.x..\r\n..G....x...\r\n...x.......\r\n...........\r\nx.....x..x.\r\n....x......\r\n.....x.....\r\n....xx.....\r\n......x....\r\nx.....x....\r\n.x..x.x....\r\n")
stage26 = Stage.create(board: "S...........\r\n.....x......\r\n......x.....\r\n.....x.....x\r\n......x..x..\r\n....x....G..\r\nx...........\r\n........x...\r\n..x.........\r\n...x...x....\r\n.......x..x.\r\nx..x.....x.x\r\n")
stage27 = Stage.create(board: "S.......x...\r\n............\r\n.x..........\r\n....x.x....x\r\n...........x\r\n...x........\r\n.....x......\r\n........G.xx\r\n...x......x.\r\nx...x......x\r\n........x...\r\n..x......x..\r\n")
stage28 = Stage.create(board: "S.x.x.x.....\r\n......x.....\r\n....x......x\r\n.......x....\r\nx...........\r\n...........x\r\nx.G.........\r\n............\r\n..xx.......x\r\n........x...\r\nx...........\r\n.x...xx.....\r\n")
stage29 = Stage.create(board: "S...xx...x...\r\n..x...x......\r\n....x.xx..x..\r\n..x.........x\r\n.............\r\n....G....x...\r\n.....x.......\r\n......x......\r\n........x....\r\n.............\r\n.............\r\n.............\r\n...x....x....\r\n")
